name: CD
on:
  - push
  - pull_request

jobs:
  
      
  macosx:
    name: Mac OS X
    runs-on: macos-11
    if: True

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.1/submodules/qtbase-everywhere-src-6.4.1.tar.xz
        tar xvf qtbase-everywhere-src-6.4.1.tar.xz
    - name: Build
      run: |
        cd qtbase-everywhere-src-6.4.1
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qtbase-everywhere-src-6.4.1
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive txz
      uses: actions/upload-artifact@v3
      with:
        name: qt6-base
        path: QtBase*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: QtBase*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}


        
 
