name: CD
on:
  - push
  - pull_request

env:
  QT_VERSION: 6.4.3
  QT_VERSION_MAJOR: 6.4

jobs:
  
      
  macosx:
    name: Mac OS X
    runs-on: macos-11
    if: True

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/${{ env.QT_VERSION_MAJOR }}/${{ env.QT_VERSION }}/submodules/qtbase-everywhere-src-${{ env.QT_VERSION }}.tar.xz
        tar xvf qtbase-everywhere-src-${{ env.QT_VERSION }}.tar.xz
    - name: Build
      run: |
        cd qtbase-everywhere-src-${{ env.QT_VERSION }}
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qtbase-everywhere-src-${{ env.QT_VERSION }}
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive txz
      uses: actions/upload-artifact@v3
      with:
        name: qt6-base
        path: QtBase*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: QtBase*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}


        
 
