name: CD
on:
  - push
  - pull_request

jobs:
  
      
  macosx:
    name: Mac OS X
    runs-on: macos-11
    if: True

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qtbase-everywhere-src-6.4.0.tar.xz
        tar xvf qtbase-everywhere-src-6.4.0.tar.xz
    - name: Build
      run: |
        cd qtbase-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        cmake ..
        
    - name: Package
      id: package
      run: |
        cd build
        cpack -G TXZ

    - name: Archive txz
      uses: actions/upload-artifact@v3
      with:
        name: qt6-base
        path: build/QtBase*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/QtBase*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}


        
 
